### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by jeremy-coleman** [notoriousb1t/vuejs-typestyle-seed#3]
Hi friend, I wanted to compare vue vs react/mobx and put this up

https://github.com/jeremy-coleman/typestyle-vue-vs-react-mobx

thanks

**Comment by notoriousb1t** [comment]
This is under MIT, so feel free to fork, clone, or remix as you like :smile:

**Comment by notoriousb1t** [comment]
Closing this for now; please re-open if you have any questions.
